### PR TITLE
do not print "..." in model.txt

### PR DESCRIPTION
**Pull request by ypwhs**

### CODE REVIEW

**Comment by pplonski** [comment]
Have you tested this? is it working correctly with your fix?

**Comment by ypwhs** [comment]
I successfully fixed the issue. 
`np.set_printoptions(threshold=np.inf)`
After adding the above code, I successfully generated a 21.4 MB model.

**Comment by pplonski** [comment]
And you can read it in C++ part?

**Comment by ypwhs** [comment]
Yes, I also apply it to iOS.
https://github.com/ypwhs/im2bw

**Pull request merged**
